logstashConfig:
 logstash.yml: |
   xpack.monitoring.enabled: false
   http.host: 0.0.0.0

logstashPipeline:
 logstash.conf: |
  input {
    rabbitmq {
      host => "rabbitmq.dev.svc"
      user => "user"
      password => "password"
      queue => "topic_kns"
      durable => true
    }
  }
  output {
    elasticsearch {
        hosts => "elasticsearch-master"
        data_stream => "true"
    }
  }
